Allow to be loaded
Avoids this error that I get:
```Traceback (most recent call last):
  File "h:\python\lib\site-packages\redbot\core\core_commands.py", line 106, in _load
    await bot.load_extension(spec)
  File "h:\python\lib\site-packages\redbot\core\bot.py", line 300, in load_extension
    await lib.setup(self)
  File "G:\Red\cogs\CogManager\cogs\antibot\__init__.py", line 7, in setup
    bot.add_cog()
TypeError: add_cog() missing 1 required positional argument: 'cog'
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x0759ED50>```